---
# File: install.yml - package installation tasks for Nomad

- name: OS packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nomad_os_packages }}"
  tags: installation

- name: Check Nomad package checksum file
  stat:
    path: "{{ role_path }}/files/nomad_{{ nomad_version }}_SHA256SUMS"
  delegate_to: localhost
  become: false
  run_once: true
  tags: installation
  register: nomad_checksum

- name: Get Nomad package checksum file
  get_url:
    url: "{{ nomad_checksum_file_url }}"
    dest: "{{ role_path }}/files/nomad_{{ nomad_version }}_SHA256SUMS"
  delegate_to: localhost
  become: false
  run_once: true
  tags: installation
  when: not nomad_checksum.stat.exists

- name: Get Nomad package checksum  # noqa 301
  shell: |
    set -o pipefail
    grep "{{ nomad_pkg }}" "{{ role_path }}/files/nomad_{{ nomad_version }}_SHA256SUMS"  | awk '{print $1}'
  delegate_to: localhost
  become: false
  register: nomad_sha256
  tags: installation

- name: Check Nomad package file
  stat: path="{{ role_path }}/files/{{ nomad_pkg }}"
  delegate_to: localhost
  become: false
  register: nomad_package

- name: Download Nomad
  get_url: url="{{ nomad_zip_url }}" dest="{{ role_path }}/files/{{ nomad_pkg }}" checksum="sha256:{{ nomad_sha256.stdout }}" timeout="42"
  delegate_to: localhost
  become: false
  tags: installation
  when: not nomad_package.stat.exists

- name: Create Temporary Directory for Extraction
  delegate_to: localhost
  tempfile:
    state: directory
    prefix: ansible-nomad.
  become: false
  register: install_temp
  tags: installation

- name: Unarchive Nomad
  unarchive: src="{{ role_path }}/files/{{ nomad_pkg }}" dest="{{ install_temp.path }}/" creates="{{ install_temp.path }}/nomad"
  delegate_to: localhost
  become: false
  tags: installation

- name: Install Nomad
  copy:
    src: "{{ install_temp.path }}/nomad"
    dest: "{{ nomad_bin_dir }}"
    owner: "{{ nomad_user }}"
    group: "{{ nomad_group }}"
    mode: 0755
  tags: installation

- name: Cleanup
  file: path="{{ install_temp.path }}" state="absent"
  delegate_to: localhost
  become: false
  tags: installation
