---
# File: selinux.yml - SELinux tasks for Nomad

# SELinux disrupts LXC (shrug)

- name: Stop SELinux enforcing
  selinux:
    state: disabled
  when: nomad_docker_enable == "true"

- name: Disable SELinux
  replace:
    dest: /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    replace: 'SELINUX=disabled'
  when: nomad_docker_enable == "true"
