---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: vmware_desktop
lint:
  name: yamllint
platforms:
  - name: instance
    box: centos/7
provisioner:
  name: ansible
  inventory:
    hosts:
      molecule:
        hosts:
          instance:
        vars:
          foo: hello
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
scenario:
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    # - idempotence  # Because we need to read a checksum file on every execution and this is caught by molecule.
    - side_effect
    - verify
    - cleanup
    - destroy
